
import sqlite3
con = sqlite3.connect('airline.db') # Warning: This file is created in the current directory
con.execute("CREATE TABLE airlines (id INTEGER PRIMARY KEY, name char(100) NOT NULL, p_class char(1) NOT NULL,status bool NOT NULL)")
con.execute("INSERT INTO airlines (name,p_class,status) VALUES ('American Airline','A',1)")
con.execute("INSERT INTO airlines (name,p_class,status) VALUES ('Alaska Airlines','C',1)")
con.execute("INSERT INTO airlines (name,p_class,status) VALUES ('Allegiant Air','B',1)")
con.execute("INSERT INTO airlines (name,p_class,status) VALUES ('Delta Air Lines','B',1)")
con.execute("INSERT INTO airlines (name,p_class,status) VALUES ('Frontier Airlines','C',1)")
con.execute("INSERT INTO airlines (name,p_class,status) VALUES ('Hawaiian Airlines','D',1)")
con.execute("INSERT INTO airlines (name,p_class,status) VALUES ('JetBlue Airways','B',1)")
con.execute("INSERT INTO airlines (name,p_class,status) VALUES ('Southwest Airlines','A',1)")
con.execute("INSERT INTO airlines (name,p_class,status) VALUES ('Spirit Airlines','C',1)")
con.execute("INSERT INTO airlines (name,p_class,status) VALUES ('Sun Country Airlines','D',1)")
con.execute("INSERT INTO airlines (name,p_class,status) VALUES ('United Airlines','A',1)")
con.execute("INSERT INTO airlines (name,p_class,status) VALUES ('Virgin America','B',1)")
con.execute("CREATE TABLE airport (id INTEGER PRIMARY KEY, name char(100) NOT NULL,flight_num INTEGER , gate char(3) NOT NULL,status bool NOT NULL)")
con.execute("INSERT INTO airport (name,flight_num,gate,status) VALUES ('Birmingham–Shuttlesworth International Airport',2560,'4',1)")
con.execute("INSERT INTO airport (name,flight_num,gate,status) VALUES ('Fresno Yosemite International Airport',7856,'5',1)")
con.execute("INSERT INTO airport (name,flight_num,gate,status) VALUES ('Miami International Airport',6329,'34',1)")
con.execute("INSERT INTO airport (name,flight_num,gate,status) VALUES ('General Downing - Peoria International Airport',4590,'43',1)")
con.execute("INSERT INTO airport (name,flight_num,gate,status) VALUES ('Fort Wayne International Airport',12950,'31',1)")
con.execute("INSERT INTO airport (name,flight_num,gate,status) VALUES ('Bangor International Airport',1597,'8',1)")
con.execute("INSERT INTO airport (name,flight_num,gate,status) VALUES ('Gerald R. Ford International Airport',3640,'9',1)")
con.execute("INSERT INTO airport (name,flight_num,gate,status) VALUES ('Kansas City International Airport',7920,'16',1)")
con.execute("INSERT INTO airport (name,flight_num,gate,status) VALUES ('McCarran International Airport',1360,'20',1)")
con.execute("INSERT INTO airport (name,flight_num,gate,status) VALUES ('John F. Kennedy International Airport',8850,'40',1)")
con.execute("INSERT INTO airport (name,flight_num,gate,status) VALUES ('Charlotte/Douglas International Airport',0569,'13',1)")
con.execute("INSERT INTO airport (name,flight_num,gate,status) VALUES ('Akron-Canton Regional Airport',3060,'2',1)")
con.execute("CREATE TABLE customers (id INTEGER PRIMARY KEY, name char(100) NOT NULL,gender char(1), address char(100) NOT NULL,status bool NOT NULL)")
con.execute("INSERT INTO customers (name,gender,address,status) VALUES ('John McCarran','M','Kent,Ohio,44240',1)")
con.execute("INSERT INTO customers (name,gender,address,status) VALUES ('Jim Carry','M','Silver Street,CA',1)")
con.execute("INSERT INTO customers (name,gender,address,status) VALUES ('Susan Lory','F','W Street, NY',1)")
con.commit()
